# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 405fa34b6ebfd400d626abd39720f6f78c134de0c0cca12c8a84d628bb0c099e38da2c79ee8a51ab4716f58f6c5c82adabb006a57d15fc6b8b5552ab81ac52f2

test:
  secret_key_base: 7094c491e56fec78c681389466f8424c0ba9517c7cfff28ed5e3c4781b8531108120ab65e7efbb4fdb365a8e843dd12fa99ad4282764e51c0ef2d0a91fe2da82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
